language: cpp
addons:
  apt:
    packages:
      - g++-10
      - clang-11

dist: focal
os:
  - linux
before_install:
  - pip3 install --user conan

script:
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-10 -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-10
  - cmake --build .
  - ctest