language: cpp
addons:
  apt:
    packages:
      - g++-10
      - clang-11

dist: focal
os:
  - linux
  - windows
  - osx
before_install:
  - pip3 install --user conan

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest