language: cpp
addons:
  apt:
    packages:
      - g++-10
      - clang-11

env:
  - CC=gcc-10 CXX=g++-10
  - CC=clang-10 CXX=clang++-10
dist: focal
os:
  - linux
  - windows
  - macos
before_install:
  - pip3 install --user conan

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest