language: cpp
addons:
  apt:
    packages:
      - g++-10
      - clang-11

dist: focal
os:
  - linux
  - windows
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install conan; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip3 install --user conan; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install conan; fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest