version: 1.0.{build}
image: 
  - Visual Studio 2019
  - Ubuntu2004
  - macos-mojave
  - macos
install:
- git submodule update --init --recursive
- pip3 install --user conan
- refreshenv
build_script:
  - cmake -B build
  - cmake --build build
  - cd build
  - ctest